// Industry Media — trade press, news, newsletters, podcasts, associations, and
// audience-measurement bodies that cover the out-of-home industry. Deliberately
// kept SEPARATE from the vendor directory (its own static dataset + /publications
// routes) so it never appears in vendor search, filters, or category pages.

export type PubType =
  | "Publication"
  | "News"
  | "Newsletter"
  | "Podcast"
  | "Association"
  | "Measurement";

export type Publication = {
  slug: string;
  name: string;
  type: PubType;
  location: string;
  cadence: string;
  founded?: string;
  website: string;
  topics: string[];
  description: string;
};

export const PUB_GROUPS: {
  key: string;
  label: string;
  blurb: string;
  types: PubType[];
}[] = [
  {
    key: "media",
    label: "Trade press, news & podcasts",
    blurb:
      "Where the out-of-home industry gets its news, analysis, and conversation.",
    types: ["Publication", "News", "Newsletter", "Podcast"],
  },
  {
    key: "orgs",
    label: "Associations & measurement",
    blurb:
      "The trade bodies and audience-measurement organizations that set standards for out-of-home.",
    types: ["Association", "Measurement"],
  },
];

// Populated from primary-source research (2026-08-14). Each entry verified from its own site.
export const PUBLICATIONS: Publication[] = [
  {"slug":"ooh-today","name":"OOH Today","type":"News","location":"United States","cadence":"Online news (updated throughout the day)","founded":"","website":"https://oohtoday.com","topics":["out-of-home","billboards","creative campaigns","OOH people","programmatic"],"description":"OOH Today is an online news outlet that positions itself as a leading source of news and information for the out-of-home advertising industry. It publishes continuously, with the homepage showing multiple posts added over the course of a single day. Coverage spans industry personnel moves and appointments, notable creative billboard executions, company partnerships and business developments, and advances in technology and programmatic advertising. Dedicated sections include Ad View (featured billboards), a podcast, classifieds, creative campaigns, OOH owners news, Tech & Research, and OOH People. The site emphasizes independent, inclusive coverage, stating that all voices in the industry, not only the loudest, should be heard. It functions as a general-interest trade news hub for media owners, agencies, and other OOH professionals rather than as a periodical magazine, and remains actively updated."},
  {"slug":"billboard-insider","name":"Billboard Insider","type":"News","location":"United States","cadence":"Daily online news","founded":"","website":"https://billboardinsider.com","topics":["billboards","out-of-home","M&A","digital signage","OOH sales"],"description":"Billboard Insider is a daily online trade news publication for the out-of-home advertising business, with a tagline describing itself as the daily news needed to run an out-of-home advertising business. It focuses on the billboard and broader OOH sector in the United States, covering business news and mergers and acquisitions, digital signage technology, sales strategies, creative campaigns, financial performance of OOH companies, and legal and regulatory issues. The site publishes proprietary industry rankings and listings, hosts a podcast, and produces specialized reference publications on subjects such as billboard law and OOH sales. Content is US-focused, with references indicating a Louisiana base. The publication targets operators, investors, and sales professionals within the out-of-home industry and is actively maintained with frequent new articles."},
  {"slug":"dailydooh","name":"DailyDOOH","type":"News","location":"London, United Kingdom","cadence":"Daily online news plus email newsletter","founded":"2007","website":"http://www.dailydooh.com","topics":["DOOH","digital signage","out-of-home","ad tech","industry events"],"description":"DailyDOOH is a long-running online publication covering the digital out-of-home (DOOH) and digital signage industries, offering insight, knowledge, and opinion. Founded in 2007 and edited by Adrian Cotterill, it is based in London and maintains a daily news category alongside a DailyDOOH Update email newsletter. Coverage includes OOH revenue and market data, media-owner and vendor announcements, digital signage deployments, awards, and industry conferences. The publication is closely tied to a portfolio of industry events, including the DailyDOOH Media Summit, the Global Digital Signage Conference, the DailyDOOH Investor Conference, and London and New York Digital Signage Weeks. Its audience is international, spanning media owners, technology suppliers, agencies, and investors. The site remains actively updated with current industry news and retains an extensive archive dating back to its founding."},
  {"slug":"ooh-insider","name":"OOH Insider","type":"Podcast","location":"United States","cadence":"Weekly podcast","founded":"2019","website":"https://www.theoohinsider.com","topics":["DOOH","programmatic","out-of-home","ad tech","audience targeting"],"description":"OOH Insider, subtitled Where DOOH Meets AdTech, is a podcast hosted by Tim Rowe that focuses on out-of-home and digital out-of-home advertising. Launched in 2019, the show describes itself as a leading source of insights into programmatic digital out-of-home and real-world OOH advertising, with each episode unpacking trends, technologies, and strategies used by brands to reach audiences through billboards, place-based media, and in-store screens. Episodes typically feature interviews with industry practitioners and cover topics such as measurement, effectiveness, hyper-targeting, and the intersection of OOH with ad technology. The podcast has grown to dozens of episodes and is distributed through Apple Podcasts, Spotify, and other platforms, accompanied by an email update for subscribers. It is aimed at marketers, media buyers, and OOH professionals seeking practical understanding of the channel."},
  {"slug":"media4growth","name":"Media4Growth","type":"Publication","location":"India","cadence":"Daily online news (with a monthly publication)","founded":"2014","website":"https://www.media4growth.com","topics":["out-of-home","DOOH","transit media","campaigns","ad tech"],"description":"Media4Growth is an India-based knowledge platform and news website dedicated to the out-of-home advertising industry across India and international markets. Founded in 2014, it delivers daily OOH and DOOH news, campaign coverage, ad-tech insights, and event updates, and also produces a monthly publication. Its audience includes brand strategists and marketers, media planners and buyers, OOH media owners, specialist and creative agencies, data and technology firms, and media consultants. Editorial coverage spans media investments, policy and regulation, people movements, agency pitches and account wins, and format-specific trends such as transit and railway media. The platform complements a wider media group that publishes the OOH title Outdoor Asia and runs industry events including the Outdoor Advertising Convention and Transit Media Talks. Media4Growth is actively updated and positions itself as a leading Indian news resource for the outdoor advertising sector."},
  {"slug":"ooh-smartbrief","name":"OOH SmartBrief","type":"Newsletter","location":"United States","cadence":"Twice-weekly email newsletter","founded":"2020","website":"https://newsletter.smartbrief.com/rest/sign-up/8EFFBE91-9541-4A31-BF9B-18B743628697","topics":["out-of-home","DOOH","ad trends","industry news","OAAA"],"description":"OOH SmartBrief is a free email news service produced by SmartBrief in partnership with the Out of Home Advertising Association of America (OAAA), launched as a twice-weekly briefing for the out-of-home advertising industry. Each edition curates and summarizes the most important news affecting the OOH sector, including advertising trends, industry insights, and thought leadership from media executives, and highlights OAAA activity such as the OBIE Awards for OOH creativity and educational and networking events. OAAA is the US national trade association for the out-of-home advertising industry, which spans billboards, street furniture, transit advertising, place-based media, and digital out-of-home (DOOH). The newsletter aggregates coverage from a range of business and trade sources into a single digest aimed at advertising and marketing professionals who want to stay current on developments in the OOH channel. It is delivered by email to free subscribers."},
  {"slug":"adweek","name":"Adweek","type":"Publication","location":"New York, United States","cadence":"Ongoing online coverage within a weekly trade publication","founded":"1978","website":"https://www.adweek.com/category/out-of-home/","topics":["out-of-home","brand marketing","billboards","transit advertising","media"],"description":"Adweek is an American advertising and marketing trade publication, first published in 1978, that covers creativity, agency and client relationships, media, and campaigns. Within its broader coverage it maintains a dedicated Out of Home category that publishes news and analysis on the out-of-home advertising industry. This section addresses industry developments, company announcements, quarterly revenue and market trends, and creative work across billboards, transit advertising, and other OOH placements, often framing OOH within wider brand-marketing and media contexts. As a general advertising-industry publication rather than an OOH-only outlet, Adweek reaches marketers, agencies, and media professionals, and its OOH reporting situates the channel alongside digital, social, and traditional media. The publication is actively maintained and the Out of Home vertical is updated with current stories, making it a mainstream press source that regularly covers the out-of-home sector."},
  {"slug":"mediapost","name":"MediaPost","type":"News","location":"New York, United States","cadence":"Daily online news and newsletters","founded":"","website":"https://www.mediapost.com/publications/tag/out-of-home/","topics":["DOOH","out-of-home","programmatic","media planning","ad spend"],"description":"MediaPost is an online publishing resource for advertising and media professionals, providing news, articles, commentary, newsletters, and events. It maintains ongoing coverage of the out-of-home and digital out-of-home (DOOH) sectors through tagged topic streams and titles such as MediaDailyNews, reporting on programmatic DOOH pricing and ad spend, media-planning trends, and technology developments. MediaPost has covered digital out-of-home over many years, from early retail and place-based video networks to today's programmatic marketplace, and its research tracks the growing inclusion of DOOH in recommended media plans. The company also runs industry events including the Digital Out-of-Home (DOOH) Insider Summit and a Digital Out-of-Home Forum, which convene planners, buyers, researchers, and creatives. As a broad ad-industry publisher rather than an OOH-only outlet, MediaPost situates out-of-home within the wider media landscape and remains actively updated with current OOH and DOOH news."},
  {"slug":"invidis","name":"invidis","type":"News","location":"Worldwide (now merged into invidis, Munich, Germany)","cadence":"Online news","founded":"2006","website":"https://invidis.com","topics":["digital signage","DOOH","LED displays","smart city","industry M&A"],"description":"Sixteen:Nine was a long-established independent online news publication covering the digital signage and digital out-of-home (DOOH) industries, founded in 2006 by Dave Haynes. As of 2026 the sixteen-nine.net domain redirects to invidis.com, and the site announces that invidis.com and sixteen-nine.net have united, consolidating their editorial coverage. The combined publication, invidis, describes itself as a magazine for digital signage, DOOH, and smart city, with global reach through dedicated regional sections for Europe, North America, Asia Pacific, the Middle East, and Latin America, plus a German-language edition at invidis.de. Coverage focuses on DOOH advertising, digital signage technology and LED displays, market analysis, and business news including mergers and acquisitions. The homepage shows frequent, current articles, indicating active daily publication. The merged outlet serves industry professionals as a business-intelligence and news resource rather than a consumer publication."},
  {"slug":"oaaa","name":"OAAA","type":"Association","location":"Washington, D.C., USA","cadence":"Trade association","founded":"","website":"https://oaaa.org","topics":["advocacy","standards","research","education","membership"],"description":"The Out of Home Advertising Association of America (OAAA) is the national trade association representing the out-of-home (OOH) advertising industry in the United States. According to its website, the organization provides its members with the tools, education, best practices, resources, and support needed to compete in the marketplace. OAAA's work spans several core areas: conducting and publishing industry research, advocating for the sector's regulatory and legislative interests, developing industry standards and guidelines, and hosting conferences, events, and educational programming. It also maintains directories of member companies and available OOH media formats to support planning and buying. Membership includes media owners, suppliers, agencies, and advertisers connected to the OOH ecosystem, from traditional billboards and transit advertising to digital out-of-home (DOOH). The association positions itself as a central resource and unified voice for the OOH industry, working to promote responsible growth, protect the medium's interests, and demonstrate its value to marketers and the broader advertising community."},
  {"slug":"woo","name":"WOO","type":"Association","location":"Zurich, Switzerland (Worldwide)","cadence":"Trade association","founded":"1959","website":"https://www.worldooh.org","topics":["global advocacy","research","events","standards","awards"],"description":"The World Out of Home Organization (WOO) describes itself as the only global Out of Home association, working to promote and improve the OOH industry on behalf of its members. Originally founded in 1959 as FEPE International, the body rebranded to World Out of Home Organization in 2019 to reflect its worldwide reach. Its membership includes major international media owners and regional OOH associations across multiple continents. WOO operates as a non-profit that reinvests surplus funds into industry initiatives. Its activities include hosting an annual global congress and regional forums, administering industry awards programs, and conducting research such as its Global Out of Home Expenditure Report. The organization also advocates for OOH advertising with public authorities and international bodies, and assists members with legislative and regulatory matters affecting the medium. Based in Zurich, Switzerland, WOO serves as a connecting point for the international OOH community, aiming to strengthen the medium's global standing, share best practices, and support the sector's continued growth and modernization."},
  {"slug":"dpaa","name":"DPAA","type":"Association","location":"New York, NY, USA","cadence":"Trade association","founded":"","website":"https://dpaaglobal.com","topics":["digital out-of-home","DOOH","research","networking","best practices"],"description":"DPAA, the Digital Place Based Advertising Association, describes itself as a leading global trade marketing association focused on driving the growth and digitization of out-of-home (OOH) media. The organization serves as a connection point among digital place-based networks, brands, agencies, ad technology companies, and the wider advertising ecosystem. According to its website, DPAA aims to help competitors collaborate and to turn industry challenges into shared opportunities. Member benefits include access to research databases, best-practice guidance, case studies, planning tools, webinars, networking events, and industry connections intended to facilitate partnerships and business development. The association concentrates particularly on digital out-of-home (DOOH) and place-based screen media, supporting members as the sector adopts data, automation, and programmatic capabilities. Headquartered in New York City, DPAA positions itself as a global community and educational resource for organizations operating in or adjacent to digital OOH, helping the medium integrate with broader omnichannel and digital advertising strategies while raising awareness of its capabilities among brands and agencies."},
  {"slug":"outsmart","name":"Outsmart","type":"Association","location":"London, United Kingdom","cadence":"Trade association","founded":"","website":"https://www.outsmart.org.uk","topics":["advocacy","standards","research","UK OOH","membership"],"description":"Outsmart is the trade body for the out-of-home (OOH) advertising industry in the United Kingdom. According to its website, the organization exists to inform, educate, and inspire people to do great work in out-of-home. It represents and connects members across the UK OOH sector, including media owners and industry participants, and works to promote the medium and support its responsible growth. Outsmart's activities center on providing industry standards, research, insights, and resources that help members and the wider market understand and make the most of OOH advertising. The body also plays a role in shaping best practice and representing the collective interests of the UK OOH industry, and it has collaborated with international standards efforts, including programmatic digital out-of-home (DOOH) initiatives alongside other industry organizations. Based in London, Outsmart offers membership to qualifying organizations in the sector and serves as a central hub and unified voice for out-of-home advertising in the UK, spanning traditional and digital formats."},
  {"slug":"commb","name":"COMMB","type":"Measurement","location":"Toronto, Canada","cadence":"Trade association / Audience measurement body","founded":"2018","website":"https://commb.ca","topics":["audience measurement","marketing","standards","Canadian OOH","data"],"description":"COMMB, the Canadian Out-of-Home Marketing and Measurement Bureau, is the national not-for-profit organization for Canada's out-of-home (OOH) industry. It was formed in 2018 through the merger of the Canadian Out-of-Home Measurement Bureau (COMB) and the Out-of-Home Marketing Association of Canada (OMAC), combining measurement and marketing functions under a single body. According to its website, COMMB's membership is made up of advertisers, agencies, programmatic technology providers, and OOH companies of all sizes. The organization focuses on two primary areas: audience measurement and collective marketing for the sector. On the measurement side, it develops methodologies and provides audience data across a range of OOH formats, including billboards, transit shelters, and digital displays, giving the market a common currency for planning and evaluating campaigns. On the marketing side, it promotes the value of the medium to advertisers and agencies. Based in Toronto, COMMB serves as the standard-setting and data authority for the Canadian OOH industry, supporting transparency, consistency, and confidence in OOH trading."},
  {"slug":"geopath","name":"Geopath","type":"Measurement","location":"New York, NY, USA","cadence":"Audience measurement body","founded":"","website":"https://geopath.org","topics":["audience measurement","impressions","insights","data","planning"],"description":"Geopath is a not-for-profit out-of-home (OOH) audience location measurement organization in the United States, describing itself as the OOH industry standard. According to its website, Geopath moves beyond traditional billboard ratings to provide audience measurement, market research, and industry insights for the OOH marketplace. The organization measures OOH advertising units across the entire country, with the capacity to deliver very large volumes of impression data each week. It provides tools such as the Geopath Insights Suite and an API that help planners, buyers, and media owners analyze audiences, plan campaigns, and evaluate performance using consistent, data-driven metrics. Geopath also conducts educational seminars and workshops covering OOH media auditing, market and advertising research, and consumer insights. Headquartered in New York City, the organization functions as a shared measurement resource governed by and serving the broader industry, including media owners, agencies, and advertisers. Its aim is to bring standardized, transparent audience data to out-of-home so the medium can be planned and traded on a comparable footing with other channels."},
  {"slug":"route","name":"Route","type":"Measurement","location":"London, United Kingdom","cadence":"Audience measurement body","founded":"","website":"https://www.route.org.uk","topics":["JIC","audience data","attention measurement","OOH planning","research"],"description":"Route is the Joint Industry Currency (JIC) for out-of-home (OOH) advertising audience measurement in Great Britain, providing audience data for adults aged 15 and over. According to its website, Route reveals who sees advertising on posters and digital screens, and its data is used to plan, trade, and evaluate OOH campaigns across the market. The measurement combines multiple data sources and methods, including GPS tracking of travel behavior, demographic surveys, eye-tracking, and volumetric information about sites, to model audiences rather than relying solely on viewable-impression counts. Route emphasizes attention-based metrics, focusing on people likely to actually see an advertisement, and projects audiences for roughly 400,000 posters and screens, with figures updated quarterly. Operated by Route Research Limited and based in London, it functions as an industry-owned currency serving media owners, agencies, and advertisers with a common, independent dataset. Route positions itself as a leading OOH measurement system internationally, aiming to give the market meaningful, comparable audience information for planning and accountability."},
  {"slug":"move","name":"MOVE","type":"Measurement","location":"Sydney, Australia","cadence":"Audience measurement body","founded":"","website":"https://www.moveoutdoor.com.au","topics":["audience measurement","visibility","exposure","Australian OOH","data"],"description":"MOVE (Measurement of Outdoor Visibility and Exposure) is Australia's out-of-home (OOH) audience measurement system, operated in connection with the Outdoor Media Association (OMA). According to its website, MOVE measures audience behavior across the full range of outdoor advertising formats, including roadside billboards, transit advertising, indoor environments such as airports and shopping centers, and place-based settings like cafes and cinemas. The system tracks a large national inventory of signs and provides audience data across many demographic profiles, capturing variations by time of day and season. Its purpose is to give advertisers, agencies, and media owners a common, independent currency for planning and evaluating OOH campaigns, quantifying reach and frequency in a consistent way across formats and markets. Coverage spans metropolitan and regional reporting areas throughout the country. By providing standardized visibility and exposure metrics, MOVE aims to demonstrate the reach and impact of the OOH medium and to support transparent, comparable trading. The system has continued to evolve with updated methodology to reflect changes in the Australian OOH landscape."},
  {"slug":"iab","name":"IAB","type":"Association","location":"New York, NY, USA","cadence":"Standards body","founded":"","website":"https://www.iab.com/guidelines/dooh-measurement-guide/","topics":["DOOH standards","measurement guide","programmatic","playbooks","guidelines"],"description":"The Interactive Advertising Bureau (IAB) is a US-based industry organization that develops standards, guidelines, and best practices for digital advertising, and it maintains a growing set of resources specific to out-of-home and digital out-of-home (DOOH). Through its guidelines program, IAB has published a DOOH Measurement Guide intended to bring clarity and consistency to a landscape it describes as challenged by inconsistent measurement standards and fragmented practices; the guide helps buyers and sellers align on a shared framework for evaluating DOOH performance, covering measurement methodologies, attribution, audience targeting, and programmatic buying. IAB has also released a Digital Out of Home and In-Store Retail Media Playbook addressing omnichannel and closed-loop measurement. On the technical side, IAB Tech Lab has standardized how DOOH inventory is handled programmatically within the OpenRTB specification, working alongside OOH bodies such as the OAAA and Outsmart. Headquartered in New York, IAB is not an OOH-only association, but these DOOH-specific standards and playbooks make it a relevant reference for the out-of-home industry's digital and programmatic development."},
];

export function getPublication(slug: string): Publication | undefined {
  return PUBLICATIONS.find((p) => p.slug === slug);
}

export function publicationsOfTypes(types: PubType[]): Publication[] {
  return PUBLICATIONS.filter((p) => types.includes(p.type)).sort((a, b) =>
    a.name.localeCompare(b.name)
  );
}
